### ISSUE TITLE
approve/update 前供使用者確認 approve/update 的內容

### ISSUE THREAD

**Issue by kth-tw** [cathayddt/bdk#21]
# ISSUE

## 說明 (Description)

新指令： `bdk org decode-envelop` 

## 種類 (Issue Type)
[x] Feature Request
[ ] Report Bug
[ ] Other

---
## 新功能 (Feature Request)
在 approve 前無法檢查內容

...

**可能的解法 (Proposed Solution)**
decode `channel-artifacts/{channelName}/{channelName}_update_envelope.pb`

**Comment by kth-tw** [comment]
指令就叫 `bdk channel decode-envelop` ?

**Comment by SecondDim** [comment]
是否可以補充，預想的完整的輸出內容？

Can you add the expected complete output content?

**Comment by kth-tw** [comment]
若是要加新Peer進system-channel，會顯示
```
Approved org: Org0Orderer
Add org to system channel: OrgNew , verify: match
```
`Approved org` 是已經 approve 的 org
`verify` 是與 `org-json` 比較的結果

**Comment by SecondDim** [comment]
建議改為輸出成三行，而且可以透過變數 --verify 控制 exit code ，如果失敗 exit 可以帶非0值

```
# bdk org decode-envelop

Approved org: Org0Orderer
Add org to system channel: OrgNew 
verify: succeeded

# exit-code: 0
```

```
# bdk org decode-envelop

Approved org: Org0Orderer
Add org to system channel: OrgNew 
verify: failed

# exit-code: 0
```

```
# bdk org decode-envelop --verify

Approved org: Org0Orderer
Add org to system channel: OrgNew 
verify: failed

# exit-code: 255
```
