### ISSUE TITLE
bdk hello error

### ISSUE THREAD

**Issue by Jim-Hong-yzu** [cathayddt/bdk#59]
# ISSUE

## 說明 (Description)
按照網頁上執行所有從原始碼安裝的指令,並執行bdk completion後,執行bdk hello出現以下訊息：
[bdk] 2022-02-17T05:33:52.585Z - warn: [production] Hello warn! { _: [Array], '$0': '/opt/homebrew/bin/bdk' }
[bdk] 2022-02-17T05:33:52.585Z - error: [production] Hello error! { _: [Array], '$0': '/opt/homebrew/bin/bdk' }

## 種類 (Issue Type)
[ ] Feature Request
[ ] Report Bug
[＊ ] Other

**Comment by kth-tw** [comment]
請問執行的環境？
OS: ???
node version: ???
node 透過什麼方法安裝？nvm? apt?...

**Comment by kth-tw** [comment]
Hello這隻指令只是測試logger而已，建議於未來的版本中移除。您測出的輸出屬於正常。請忽略即可。
