### ISSUE TITLE
bdk create channel error

### ISSUE THREAD

**Issue by xuyangm** [cathayddt/bdk#63]
# ISSUE

## 說明 (Description)

請簡單說明此 issue。

Please include a summary of the issue.

## 種類 (Issue Type)
[ ] Feature Request
[ ] Report Bug
[x] Other

## 通報問題 (Report Bug)
**重現步驟 (Steps to Reproduce)**
1. bdk network create --test-network 
2. bdk orderer up -i 
3. bdk peer up -i
4. bdk channel create -i

**測試環境 (Environment)**:
* OS: Mac
* NodeJS Version:
* NPM Version:
* Docker Version:

**應呈現結果 (Expected Behavior)**

成功创建Channel

**實際呈現結果 (Resulted Behavior)**

<img width="570" alt="Screenshot 2022-04-26 at 14 27 19" src="https://user-images.githubusercontent.com/16891612/165299808-6e4b7782-80ef-4523-98b1-265d80cd8941.png">

---

## 其他說明 (Additional Context)

**Comment by kth-tw** [comment]
請參考這部份文件
https://github.com/cathayddt/bdk/blob/master/docs/EXAMPLE.md#step-3%E5%BB%BA%E7%AB%8B-channel
在環境變數或 `~/.bdk/.env` 中設定 `BDK_ORG_NAME `, `BDK_ORG_DOMAIN `, 與`BDK_HOSTNAME `
