### ISSUE TITLE
請教一些非技術的問題, 如何因應關於機敏資料定義的改變

### ISSUE THREAD

**Issue by shingo0620** [cathayddt/bdk#69]
# 關於機敏資料

## 說明 (Description)

今天參加TBW2022聽到Eric, Evan精彩的talk, 想請教一下目前已經實際開始應用的場景是否有考慮如果一些已經上鏈的資料, 在未來法律修改突然被定義成機敏資料必須要讓使用者可以完整刪除這樣的情況? 畢竟台灣個資法和國外個資法也還是有不同, 也不排除外來對個資的處理也有可能會越來越嚴苛或甚至必須要完全遵守GDPR..

**Comment by ericlin716** [comment]
不管是對於 GDPR 還是台灣個資法，我們在設計時應該盡量避免任何相關於個資方面的資料上鏈，若真的要使用到敏感性個資資料建議採用混合型式的架構(在 TBW Bootcamp 中有提到 )來處理資料，或是使用加密方法來加密鏈上敏感性資料如 ZK等等。
